name: 'Terraform'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Initialize
      run: |
        terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -backend-config="bucket=${{ secrets.BUCKET }}" \
          -backend-config="key=${{ secrets.KEY }}" \
          -backend-config="region=${{ secrets.REGION }}"

    - name: Create Terraform Plan Artifact
      run: |
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export AWS_REGION="${{ secrets.REGION }}"
        terraform import aws_s3_bucket.this.arn [arn:aws:s3:::rtslab-demo-tfstate]
        terraform plan -out tfplan

#    - name: Terraform Apply
#      run: |
#          terraform apply tfplan
